# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
name: core-kurrent
x-bake: true

services:
  core-kurrent:
    container_name: core-kurrent
    hostname: core-kurrent
    image: kurrentplatform/kurrentdb:25.0.0-experimental-arm64-8.0-jammy
    env_file:
      - ./.env
    ports:
      - "${KURRENTDB_NODE_PORT}:${KURRENTDB_NODE_PORT}"
    volumes:
      - type: volume
        source: kurrentdb-volume-data
        target: /var/lib/kurrentdb
      - type: volume
        source: kurrentdb-volume-logs
        target: /var/log/kurrentdb
    networks:
      - core-kurrent-private
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:${KURRENTDB_NODE_PORT}/info || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  kurrentdb-volume-data:
  kurrentdb-volume-logs:

networks:
  core-kurrent-private:
    name: core-kurrent-private
    external: false
    attachable: true
